name: PHP Tests

on: [push, pull_request]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Run Linter
      run: ./vendor/bin/phpcs --standard=PSR12 path/to/your/plugin
    - name: Run PHPUnit Tests
      run: ./vendor/bin/phpunit
