jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [7.4, 8.0]
        wordpress-version: [5.7, 5.8, latest]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, json, mysqli

      - name: Clone wordpress-develop
        run: |
          git clone --depth=1 https://github.com/WordPress/wordpress-develop.git /tmp/wordpress-develop

      - name: Install WordPress test suite
        run: |
          bash /tmp/wordpress-develop/tests/phpunit/includes/install-wp-tests.sh wordpress_test root root 127.0.0.1 ${{ matrix.wordpress-version }}

      - name: Copy plugin to WordPress
        run: |
          mkdir -p /tmp/wordpress-develop/src/wp-content/plugins/cool-kids-network
          cp -r . /tmp/wordpress-develop/src/wp-content/plugins/cool-kids-network

      - name: Run PHPUnit tests
        run: |
          cd /tmp/wordpress-develop/src/wp-content/plugins/cool-kids-network
          phpunit --configuration phpunit.xml.dist